03-objects-arrays-intro-to-testing
js-tasks-ru/js-20200821-3_evgeniy-nagalskiy pull request #3
Opened 2020-09-01 08:49 UTC by DrShpongle

2020-09-01 08:58 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
createGetter
+ should return existed properties
+ should return "undefined" for properties which does not exist
+ gets obj.property
+ returns undefined for no property
+ gets obj.nested.property
+ returns undefined for no nested.property
+ gets more.nested.property
```
```diff
trimSymbols
+ should remove an identical consecutive characters that exceed the specified size
+ should return empty string if it was passed to function like an argument
+ should return empty string if "size" equal 0
+ should return the same string if "size" parameter wasn't specified
```
```diff
invertObj
+ should swap keys and values and return new object
+ should return empty object if was passed object without values
+ should return "undefined" if object wasn't passed
```
```diff
uniq
+ should return array with uniq values
+ should return empty array if was passed array without values
+ should return empty array if arguments wasn't passed
```

Добавляю преподавателя (@dosandk) для код-ревью, посмотрим что он скажет :)

2020-09-01 10:15 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/3-trim-symbols/index.js
> +  const chunks = string.split('').reduce(
очень сложно выглядит решение, обратите внимание на то которое будем сегодня разбирать на занятии

2020-09-01 10:16 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return arr
эту функцию следует исправить, посмотрите в сторону `Set` https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set

2020-09-01 10:16 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/1-create-getter/index.js
> +  let propsArr = path.split('.')
good 👍

2020-09-01 10:16 UTC, dosandk commented on 03-objects-arrays-intro-to-testing/2-invert-object/index.js
>  export function invertObj(obj) {
good 👍

2020-09-01 10:16 UTC, dosandk requested changes
необходимо внести правки согласно комментариям

2020-09-01 10:30 UTC, DrShpongle commented on 03-objects-arrays-intro-to-testing/4-uniq/index.js
> +  return arr
Наверное, вы имеете в виду эту особенность:
Основная «изюминка» – это то, что при повторных вызовах set.add() с одним и тем же значением ничего не происходит, за счёт этого как раз и получается, что каждое значение появляется один раз.

2020-09-01 10:58 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-02 10:30 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2020-09-03 14:35 UTC, dosandk approved these changes
good 👍

2020-09-03 14:36 UTC, merged